### ISSUE TITLE
handle forwarded messages

### ISSUE THREAD

**Issue by titaniumbones** [jeremy-compostella/org-msg#11]
last in a whole bunch of reports (sorry!). I'm pretty sure that org-msg chokes on forwarded messages, because of this line:

```
	     (temp-files (org-msg-get-prop "reply-to"))
```

which forwarded messages do not contain. Maybe there's a way to use `References` in an analogous way? Though that does seem somewhat more complex.

**Comment by jeremy-compostella** [comment]
When I want to forward, I just reply and change the recipient list.  
Would that work for your mu4e based use-case ?

**Comment by titaniumbones** [comment]
Yes, I think that would work, though in the long run it would be nice to have something more robust, I guess.

**Comment by guibor** [comment]
My solution - rewrite org-msg-post-setup so that it includes the reply-to, and make sure the reply-to appears in the message even when forwarding - by changing mu4e~draft-forward-construct accordingly in mu4e-draft.el (though adding advice would have been a better solution)


```

(defun org-msg-post-setup (&rest _args)
  "Transform the current `message' buffer into a OrgMsg buffer.
If the current `message' buffer is a reply, the
`org-msg-separator' string is inserted at the end of the editing
area."
  (message-goto-body)
  (let ((new (not (and (message-fetch-field "to")
                       (message-fetch-field "subject"))))
        (with-original (not (= (point) (point-max))))
        (reply-to))
    (when (or new (org-msg-mua-call 'article-htmlp))
      (setq reply-to (org-msg-mua-call 'save-article-for-reply))
      (insert (org-msg-header reply-to))
      (when org-msg-greeting-fmt
        (insert (format org-msg-greeting-fmt
                        (if new
                            ""
                          (org-msg-get-to-first-name)))))
      (save-excursion
        (when with-original
          (save-excursion
            (insert "\n\n" org-msg-separator "\n")
            (delete-region (line-beginning-position)
                           (1+ (line-end-position)))
            (save-excursion
              (while (re-search-forward "^>+ *" nil t)
                (replace-match "")))
            (org-escape-code-in-region (point) (point-max))))
        (when org-msg-signature
          (insert org-msg-signature))
        (org-msg-edit-mode)))
    (if new
        (message-goto-to)
      (org-msg-goto-body))))
```

**Comment by jeremy-compostella** [comment]
Hi **Michael-David**,

I tried to take your suggestion of `org-msg-post-setup()` into account with [Add limited support for mail forwarding](https://github.com/jeremy-compostella/org-msg/commit/c8fca6929704b9a8019d8eeb32ebe0d3312b5767).  Let me know if it helps in your case.

Regards,

-**Jeremy**   
*One Emacs to rule them all*
