### ISSUE TITLE
OrgMsg hangs 

### ISSUE THREAD

**Issue by Chris00** [jeremy-compostella/org-msg#111]
The experimental branch of OrgMsg (commit 5945c6a) hangs on [this message](https://github.com/jeremy-compostella/org-msg/files/6504321/msg.txt) when pressing <kbd>C-c C-c</kbd> to send it or when trying to render it with `org-msg-preview`.  I have `org-msg-convert-citation` set to `t`.

**Comment by jeremy-compostella** [comment]
The patch I pushed on the `experimental` branch should fix this. A message such as the following should not be a problem anymore. 

```
[...]
> Ansi qu'une excellente nuit !
```
