### ISSUE TITLE
Paragraph wrapping and &npsb

### ISSUE THREAD

**Issue by roblem** [jeremy-compostella/org-msg#117]
Consider an email body having long paragraphs like this:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id faucibus nisl tincidunt eget nullam. Neque sodales ut etiam sit. Ac auctor augue mauris augue neque gravida in. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Congue eu consequat ac felis donec. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Justo laoreet sit amet cursus sit amet dictum sit. Nulla facilisi nullam vehicula ipsum a arcu cursus. Erat nam at lectus urna duis. Ultricies tristique nulla aliquet enim tortor at auctor. Risus feugiat in ante metus dictum at tempor. Arcu risus quis varius quam quisque. Massa ultricies mi quis hendrerit dolor magna. Eu tincidunt tortor aliquam nulla facilisi. Cras fermentum odio eu feugiat. Interdum velit euismod in pellentesque massa placerat.
```
This previews as 

![org-msg-preview](https://user-images.githubusercontent.com/1871086/121767932-b7bcd380-cb5b-11eb-814b-900a74e8977b.png)

And I can see the html for these paragraphs is like this:
```html
Lorem&nbsp;ipsum&nbsp;dolor&nbsp;sit&nbsp;amet,&nbsp;consectetur&nbsp;
```

If I manually remove the `&npsp` from the generated html, we get wrapping as you would expect:
![org-msg-preview-no-nbsp](https://user-images.githubusercontent.com/1871086/121768124-ade7a000-cb5c-11eb-9eb8-aa0f0a6a2c6e.png)

I noticed that even with the `&nbsp` character, services like gmail and client such as Thunderbird seem to override it ok and wrap the text.  Others like Protonmail, however do not and it looks like this:
![proton-mail-wrapping](https://user-images.githubusercontent.com/1871086/121768031-3ca7ed00-cb5c-11eb-90e4-e3f7bbb2183d.png)

**Comment by obar** [comment]
Did your lorem ipsum source have those non-breaking spaces? When I copy your message text into a draft and preview it, it wraps just as expected because there aren't any non-breaking spaces in what made it to github.

Of course you can use `lorem-ipsum.el` from melpa to make however many sentences or paragraphs you'd like, without hidden characters ;)

**Comment by roblem** [comment]
I can't reproduce this anymore whether I use the original website I pasted paragraphs in from or if I use the package you suggest. So closing.  Apologies.
