### ISSUE TITLE
`org-msg-post-setup` chokes in  mu4e if message is not currently open

### ISSUE THREAD

**Issue by titaniumbones** [jeremy-compostella/org-msg#12]
`org-msg-post-setup` calls `org-msg-save-article-for-reply-mu4e` in mu4e mode, which assumes that the buffer `*mu4e-view*` is currently open. However, that may not be the case.  If it's not, the method we currently have for inserting message contents will fail.  

because `org-msg-post-setup` is called at the end of `mu4e-compose` -- the post-execution hook -- it's a bit late at that point to o something simple like just call `mu4e-headers-view-message`. There's a long sequnce of bouncing function calls in mu4e's window-drawing call stack, but it might be possible to extract the `docid` attribute and use it to track down the html body. Maybe it's worth asking on`mu-discuss`?

**Comment by jeremy-compostella** [comment]
I am a bit lost here.  What is the status of this issue ?

**Comment by titaniumbones** [comment]
Sorry to leave you hanging. From what I can tell, thee status is "still a problem".  Calling `mu4e-compose-reply` from the mu4e mailbox summary buffer (`*mu4e-headers*`) when ~mu4e-view~ is not open will cause an error as seen below, because `org-msg-article-htmlp-mu4e` will try to open and parse an existing `*mu4e-view*` buffer to test if the message is html.  My guess is that there's a lower-level function available somewhere that would allow org-msg to parse the underlying message itself, but I haven't had a chance to look mroe closely at the mu4e code.  When I get a change I can try to ask o nthe mu-discuss mailing list, or perhaps there's someone else better positioned to fix this... 

```emacs-lisp
Debugger entered--Lisp error: (error "No buffer named *mu4e-view*")
  set-buffer("*mu4e-view*")
  (save-current-buffer (set-buffer mu4e~view-buffer-name) (if (mu4e-message-field-at-point :body-html) (progn t)))
  org-msg-article-htmlp-mu4e()
  apply(org-msg-article-htmlp-mu4e nil)
  (progn (apply fun arg))
  (if (functionp fun) (progn (apply fun arg)))
  (let ((fun (intern (format "org-msg-%s-%s" sym mua)))) (if (functionp fun) (progn (apply fun arg))))
  (if mua (let ((fun (intern (format "org-msg-%s-%s" sym mua)))) (if (functionp fun) (progn (apply fun arg)))) (error "Backend not found"))
  (let ((mua (assoc-default mail-user-agent org-msg-supported-mua))) (if mua (let ((fun (intern (format "org-msg-%s-%s" sym mua)))) (if (functionp fun) (progn (apply fun arg)))) (error "Backend not found")))
  org-msg-mua-call(article-htmlp)
  (or new (org-msg-mua-call 'article-htmlp))
  (if (or new (org-msg-mua-call 'article-htmlp)) (progn (if new nil (setq reply-to (org-msg-mua-call 'save-article-for-reply))) (insert (org-msg-header reply-to)) (if org-msg-greeting-fmt (progn (insert (format org-msg-greeting-fmt (if new "" (org-msg-get-to-first-name)))))) (save-excursion (if with-original (progn (save-excursion (insert "\n\n" org-msg-separator "\n") (delete-region (line-beginning-position) (1+ ...)) (save-excursion (while ... ...)) (org-escape-code-in-region (point) (point-max))))) (if org-msg-signature (progn (insert org-msg-signature))) (org-msg-edit-mode))))
  (let ((new (not (and (message-fetch-field "to") (message-fetch-field "subject")))) (with-original (not (= (point) (point-max)))) (reply-to)) (if (or new (org-msg-mua-call 'article-htmlp)) (progn (if new nil (setq reply-to (org-msg-mua-call 'save-article-for-reply))) (insert (org-msg-header reply-to)) (if org-msg-greeting-fmt (progn (insert (format org-msg-greeting-fmt (if new "" ...))))) (save-excursion (if with-original (progn (save-excursion (insert "\n\n" org-msg-separator "\n") (delete-region ... ...) (save-excursion ...) (org-escape-code-in-region ... ...)))) (if org-msg-signature (progn (insert org-msg-signature))) (org-msg-edit-mode)))) (if new (message-goto-to) (org-msg-goto-body)))
  org-msg-post-setup()
  run-hooks(change-major-mode-after-body-hook text-mode-hook message-mode-hook mu4e-compose-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook message-mode-hook mu4e-compose-mode-hook))
  run-mode-hooks(mu4e-compose-mode-hook)
  mu4e-compose-mode()
  mu4e~compose-handler(reply (:docid 102611 :subject "Firefox Monitor found your email in a new data bre..." :date (24027 26864 0) :size 27057 :message-id "0101016ea111eb02-4c624c51-ce86-42e2-853b-214d985fd..." :path "/home/matt/UofTMail/inbox/cur/1574686684_1.205752...." :maildir "/inbox" :priority normal :flags (replied seen) :parts ((:index 1 :name "1.msgpart" :mime-type "text/html" :type (leaf) :attachment nil :size 19769)) :from (("Firefox Monitor" . "breach-alerts@mozilla.com")) :to ((nil . "matt.price@utoronto.ca")) :body-html "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Stric...") nil)
  mu4e~proc-filter(#<process  *mu4e-proc*> "rgin: 0px; text-decoration: none; line-height: 1.5...")
```

**Comment by titaniumbones** [comment]
Poking around just a little bit, I think that the call to `mu4e-message-field-at-point :body-html) would succeed *without* the `(set-buffer mu4e~view-buffer-name ...)` if it were attached to `mu4e-compose-pre-hook` instead of `mu4e-compose-hook`. That is, it would be easy to get access to the info if we could store information in a variable that persists from pre-composition to post-composition. Since the buffer changes across the composition process, I guess the variable couldn't be buffer-local, so potentially you could end up with the wrong message in the compose buffer. 

If this method is not practical it might be possible to get the msg object via the msg id, which I think is preserved in the "References" header, but I haven't yet found out how

**Comment by guibor** [comment]
Not perfect, but this seemed to help

```
(defun mu4e-headers-compose-reply ()
        (interactive)
        (mu4e-headers-view-message)
        (switch-to-buffer "*mu4e-headers*")
        (mu4e-compose-reply)
        (org-msg-goto-body)
        )

      (defun mu4e-headers-compose-forward ()
        (interactive)
        (mu4e-headers-view-message)
        (switch-to-buffer "*mu4e-headers*")
        (mu4e-compose-forward)        
        )

      (define-key mu4e-headers-mode-map (kbd "R") 'mu4e-headers-compose-reply)
      (define-key mu4e-view-mode-map (kbd "F") 'mu4e-headers-compose-forward)
```

**Comment by jeremy-compostella** [comment]
The method based on pre-composition hook and composition hook is not very elegant but it should work.  Feel free to submit a patch one you have something which work and does not require a hack in mu4e.

**Comment by titaniumbones** [comment]
Waiting for a response form mu-discuss list to see if  I can get access to the msg object through the `References` header instead -- this seems more sustainable to me. However, at present mu4e filters the mu process output in a way that seems to make it impossible to get the raw object directly.
