### ISSUE TITLE
org-msg swallowing newlines

### ISSUE THREAD

**Issue by jsilve24** [jeremy-compostella/org-msg#123]
I would like to have a simple email signature as a yassnippet (worked great in basic mu4e), it looked something like:

```
jsilve24
Title blah blah blah
Office location

E my email
T my phone number
W my website
```

But with org-msg this the newlines are not respected and this gets compacted to 

```
jsilve24 Title blah blah blah Office location

E my email T my phone number W my website
```

Whats the best way to handle this? Is this a bug or is there some option I am missing? 

Thank you very much!

**Comment by jeremy-compostella** [comment]
This is not a *OrgMsg* issue, this is Emacs org mode default behavior. You can customize this behavior. In the documentation of OrgMsg you'll find my default configuration with an option taking care of this (see my `org-msg-options` value)

**Comment by jsilve24** [comment]
Oh wonderful!

Thank you and appologies for the off topic question.

Is that the \\n:t flag by any chance? I had tried playing around with various settings in your configuration but must have missed the crucial one.

**Comment by jsilve24** [comment]
Ahhh. when you want to paste it into the org-msg header you don't need the extra escape on the backslash. 

`\n:t` worked as expected. Thank you!
