### ISSUE TITLE
Alert if no attachments in an email where there should be

### ISSUE THREAD

**Issue by Hugo-Heagren** [jeremy-compostella/org-msg#128]
I've just managed to send an email in which I mention the attached files, but forgot to actually attach them. I seem to do this far too much. Something I really miss from when I used to use neomutt was being alerted when an email contained a phrase like 'attached files' or similar, but had no attachments. It would be good (and I think, not too difficult) to implement something like this in org-msg. The predicate to check whether the email 'should' have attachments could be user-configurable too, so people could write their own functions for this if they liked.

**Comment by jeremy-compostella** [comment]
Let's start with something simple (see patch above).

**Comment by Hugo-Heagren** [comment]
Looks great to me!
