### ISSUE TITLE
error when the signature contains a double pipe character.

### ISSUE THREAD

**Issue by DarkBuffalo** [jeremy-compostella/org-msg#129]
Hi, thanks for this package, good Job!

When the signature contains a double pipe it is transcribed as a table.
Is there a solution to make it text only when converting? 

example of signature: 
```
sofiefonsec@gnu.xyz
|          ├ web  ┤
├github/lab┘      |
└      email      ┘
```

**Comment by jeremy-compostella** [comment]
This is not really org-msg issue but rather an org-mode question. Have you tried to use `\vbar` instead `|` ?

**Comment by DarkBuffalo** [comment]
thanks
