### ISSUE TITLE
[questen] HTML signature 

### ISSUE THREAD

**Issue by cslux** [jeremy-compostella/org-msg#13]
I have to use a specific HTML signature at work. It is already written in HTML. But every attempt to send it fails. It always arrives as HTML code. Do you know how I can achieve this?

Thank you!

**Comment by jeremy-compostella** [comment]
Have you tried something like this?
https://orgmode.org/manual/Quoting-HTML-tags.html

Jeremy

**Comment by cslux** [comment]
Awesome, it works.

Thank you Jeremy!
