### ISSUE TITLE
Outlook displays org-msg emails in a narrow column

### ISSUE THREAD

**Issue by TS-CUBED** [jeremy-compostella/org-msg#131]
When I send an `org-msg` email through `mu4e` the message gets encoded as html fine.

Most clients (including the Outlook desktop app) will display these emails nicely. 

However, the Outlook online client, and the Outlook mobile app, will display them in a narrow column, rather than the fixed column width of 90 characters that the HTML code has.

Not sure how to provide debugging info here, since the problem seems to be on MS's side, but maybe somebody knows which HTML setting could cause this.

Running Doom Emacs V 3.0.0beta

**Comment by jeremy-compostella** [comment]
Could you look at #59 to see if this is similar ?

**Comment by TS-CUBED** [comment]
This is indeed the same effect.
Looking at the HTML source of the offending emails, they contain lines:

`<p style="text-decoration:none;line-height:1.4;margin-top:10px;margin-bottom:0px;font-size:11pt;max-width:90ch;">`

so there is a maximum width given, which is what seemed to have caused the problem in #59 

The old issue was from 2020 and there seems to have been a commit addressing it. So what would be the best way to address that? 

Will need to check which version of `org-msg` Doom pulls in currently. But there was a recent update, so I assume it would be a relatively up-to-date one.

**Comment by TS-CUBED** [comment]
Hello, this helped me hunt down the problem. 
The bug is in the Doom `config.el` for the org-msg part of Doom's `mu4e` module. Not in the `org-msg.el` that comes with `org-msg`.

So I'll raise an issue with Doom Emacs and close this one.

**Comment by eddiegroves** [comment]
I fixed this for now by overriding Doom's custom styles. I preferred the ones org-msg provides by default anyway.

```
(setq org-msg-enforce-css org-msg-default-style)
```
