### ISSUE TITLE
Error export code block with fringe folding symbols

### ISSUE THREAD

**Issue by danielfleischer** [jeremy-compostella/org-msg#150]
Writing a python code block, edit it using `C-c '`, having elpy enabled puts folding symbols on functions in the fringe. Somehow it causes an error when trying to create an HTML email; e.g. when calling `org-msg-preview` one gets `substring: Args out of range: " ", 0, -3`. 

Tested the cause by disabling elpy, removing code that has a folding sign, disabling folding in elpy customization. It all points to the fringe indicators. 

Thanks!

**Comment by jeremy-compostella** [comment]
I could not reproduce this issue with the following simple python src block:

```
#+begin_src python
  def toto():
      pass

  def titi(data_list):
      for item in data_list.item():
        print(item)
#+end_src
```
I hit `C-c '` Then on a function I call `elpy-folding-toggle-at-point`. The function is folded. I hit `C-c '` it goes back to the mail composer buffer in which the function is unfolded.

**Comment by danielfleischer** [comment]
But does `org-msg-preview` work with HTML output?

**Comment by danielfleischer** [comment]
OK, it's a general org html export issue; taking it upstream.
