### ISSUE TITLE
Not adding signature nor using org-msg-options under mu4e

### ISSUE THREAD

**Issue by zamansky** [jeremy-compostella/org-msg#16]
I'm sending under mu4e.

I manually activate org-msg-edit-mode and the message is indeed formatted and sent out correctly but I don't get my signature and the org-msg-options aren't used.

If I manually put in the options by adding an:

#+OPTIONS: etc.

line at the top, the options to take effect.

**Comment by jeremy-compostella** [comment]
Hi,

This is the expected behavior. If you don't activate `org-msg-mode`, the hooks for `mu4e` don't get added and called when you start composing a message with `mu4e`.

May I know you don't activate `org-msg-mode` ?

Regards,
**Jeremy**

**Comment by zamansky** [comment]
Yes - I set it as a global mode. Here's the relevant part of my startup file

```

(use-package org-msg
:ensure t
:config
(setq org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil")
(setq org-msg-startup "hidestars indent inlineimages")
(setq org-msg-greeting-fmt "\nmHi %s,\n\n")
(setq org-msg-greeting-fmt-mailto t)
(setq org-msg-signature "

Regards,

#+begin_signature
-- *Mike* \\\\
#+end_signature")
(org-msg-mode)
)
```

Which is basically taken from the docs.

I also double checked the modes when editing a message (using c-h m) and it's in org-msg mode.

Thanks

**Comment by jeremy-compostella** [comment]
Hi **Mike**,

Could you try the solution based on setting the `mail-user-agent` variable in #15 work for you. I suspect that something has changed with regard to this variable setting which make `org-msg` don't realize that you are using `mu4e`.

FYI, I don't use `mu4e`, I use `gnus`. Any help to resolve `mu4e` specific issues is very welcome.

Regards,
**Jeremy**

**Comment by jeremy-compostella** [comment]
Hi **Mike**,

Does solution of #15 work for you ?

Regards,
**Jeremy**

**Comment by zamansky** [comment]
Yes - it did!!!!! Thanks!!!

**Comment by jeremy-compostella** [comment]
Good. Now, I, we need to find a two fix instead of this workaround.

**Comment by jeremy-compostella** [comment]
Hi **Mike**,

it turns out this is not a workaround.  As a `mu4e` user you have to set this variable (https://www.djcbsoftware.nl/code/mu/mu4e/Emacs-default.html#Emacs-default)

`(setq mail-user-agent 'mu4e-user-agent)` 

Let me know if this line of code works for you.  I am going to add this information to the documentation since two `mu4e` users struggled with this.

Regards,
**Jeremy**

**Comment by jeremy-compostella** [comment]
Hi **Mike**,

It turns out that the Mail User Agent variable has to be defined by the end-user.  I have improved the documentation of **OrgMsg** to reflect this requirement.  Do you mind reviewing the documentation on the [experimental branch](https://github.com/jeremy-compostella/org-msg/tree/experimental) and let me know if it is clear and accurate enough ?

Regards,

**Jeremy**   
*One Emacs to rule them all*

**Comment by zamansky** [comment]
Certainly but I probably won't get to it until Thursday afternoon or Friday
morning.

Thanks!!!
Mike
http://cestlaz.github.com

**Comment by jeremy-compostella** [comment]
That's fine.  As long as you get to it this week.  I would like to push it on the master branch end of this week.

**Comment by zamansky** [comment]
Just installed the experimental branch, tested it by following the docs and it all worked for me!!!

Thanks for being so super responsive on this (and sorry I couldn't be the same as I was the one raising the issue to begin with).

using emacs video on org-msg coming soon.

**Comment by jeremy-compostella** [comment]
Thanks you for your review. I pushed on the master branch.

If you make a video publicly available, let me know, I could add a link from the documentation.

**Comment by zamansky** [comment]
Jeremy,

Just wanted to let you know, I posted a video on org-msg (
https://cestlaz.github.io/post/using-emacs-61-org-msg/).

Thanks for the great package.

**Comment by jeremy-compostella** [comment]
**Mike**,

I read the article and watched the video.  This is an interesting presentation but I don't think that this is not centered enough on the `org-msg` to make it documentation material.

I appreciate that you shared your experience with `org-msg` and I got a bunch of new tickets as a follow up from your fans which probably more users :)

Regards,
**Jeremy**
