### ISSUE TITLE
Nothing Happens with Spacemacs

### ISSUE THREAD

**Issue by NatHarari** [jeremy-compostella/org-msg#17]
Hey there,
I saw the package demoed on Mike Zamansky's video and tried installing it on Spacemacs. I get no errors at all installing it, but when I fire up mu4e, I have nothing going on with org-msg. No pre-installed lines of toc stuff or anything else etc... I did an M-x org-msg mode and that works and it is active, but it doesn't display in org-mode style when writing a message in mu4e.

My mu4e version is 1.2.0 C and my Spacemacs version is the latest pull on develop version 0.3 - whatever the latest version is (it's constantly changing).

I know that org-msg is installed because org-msg shows up with M-x org-msg mode. I put org-msg package in 'dotspacemacs-additional-packages' and then I configured it in dotspacemacs/user-config() with just a copy/paste of your own config on your page here. I checked to make sure that mu4e is my mail agent (it is).

So I'm sort of at a loss about what I'm doing wrong. Just curious. If you don't have time to figure it out, I'll post about it in the Spacemacs page. :) I just figured I'd try here first.

Thanks!

**Comment by jeremy-compostella** [comment]
Hi **Nathaniel**,

> I did an M-x org-msg mode and that works and it is active, but it doesn't display in org-mode style when writing a message in mu4e.

What is the `major-mode` variable value when you compose a message with mu4e and `org-msg-mode` enabled ?

> My mu4e version is 1.2.0 C and my Spacemacs version is the latest pull on develop version 0.3 - whatever the latest version is (it's constantly changing).

I don't use `spacemacs` and I don't use `mu4e`.  I only extended it to support `mu4e` because it was not complicated and I got help from a `mu4e` fluent enough in emacslisp.

> I know that org-msg is installed because org-msg shows up with M-x org-msg mode. I put org-msg package in 'dotspacemacs-additional-packages' and then I configured it in dotspacemacs/user-config() with just a copy/paste of your own config on your page here. I checked to make sure that mu4e is my mail agent (it is).

If `mail-user-agent` is set to `"mu4e"`, `org-msg-mode` should call `org-msg-mode-mu4e` which should set the appropriate hook.  What is the values of `mu4e-compose-mode-hook` ?

    930  (defun org-msg-mode-mu4e ()
    931    "Setup the hook for mu4e mail user agent."
    932    (if org-msg-mode
    933        (add-hook 'mu4e-compose-mode-hook 'org-msg-post-setup)
    934      (remove-hook 'mu4e-compose-mode-hook 'org-msg-post-setup)))

Regards,

--**Jeremy**   
*One Emacs to rule them all*

**Comment by NatHarari** [comment]
Thanks! It was the hook I needed. Works flawlessly now. I just put that in with a copy/paste (sans line numbers of course) into my .spacemacs file in the user config section right below the (org-msg-mode) and reloaded and everything works perfectly. Can't thank you enough.  Thank you again for everything. :)

**Comment by gyhor** [comment]
@NatHarari Natharari
Did you configured the mail-user-agent? If not org-msg does not recognize the mailer.
Just insert this line into .spacemacs in the part of your mu4e configuration:
```
(setq 'mail-user-agent 'mu4e-user-agent)
```
or direct in dotspacemacs-configuration-layers()
for example like this
``` 
(mu4e :variables
           ;; set mail user agent
           mail-user-agent 'mu4e-user-agent
           mu4e-enable-notifications t"
           mu4e-compose-dont-reply-to-self t
           mu4e-view-show-images t
           ;; every new email composition gets its own frame!
           mu4e-enable-mode-line t
           mu4e-compose-in-new-frame t
           mu4e-headers-include-related t
           mu4e-headers-visible-lines 20
           mu4e-use-fancy-chars t
           ;; enable inline images
           mu4e-view-show-images t
           mu4e-attachment-dir  "~/Downloads"
           mu4e-view-prefer-html t
           mu4e-headers-auto-update nil
           mu4e-compose-signature-auto-include nil
           mu4e-compose-format-flowed t
           ;; mu4e-split-view 'horizontal
           ;; don't keep message buffers around
           message-kill-buffer-on-exit t
           ;;rename files when moving
           ;;NEEDED FOR MBSYNC
           mu4e-change-filenames-when-moving t
           ;; show full addresses in view message (instead of just names)
           ;; toggle per name with M-RET
           mu4e-view-show-addresses 't
           ;; don't ask when quitting
           mu4e-confirm-quit nil
           )
```

**Comment by NatHarari** [comment]
Yeah, I did the (setq 'mail-user-agent 'mu4e-user-agent) ages ago. :) Don't worry, it seems to work fine. I just needed the hook. It works wonderfully, in fact. I tested it out with a nice Header/subheader thing, a nice table, bolded text etc.... it looked beautiful. Thank you very much. It looks absolutely professional. I'm loving it. :)

**Comment by jeremy-compostella** [comment]
Hi **Nathaniel**,

I understand that it works for you by adding the hook manually but this is very intrigging to me and I would appreciate if you could investigate further because if the Mail User Agent is set properly the `org-msg-mode` function should call the `org-msg-mode-mu4e` which should set the hook automatically.  Maybe adding some `message` instrumentation in the org-msg code would help.

I don't want people to start workarounding by setting hooks manually if there is an actual bug.

Regards,
**Jeremy**

**Comment by NatHarari** [comment]
Ah! Sorry, I misunderstood.
I'll email you for specifics. :)

**Comment by ECon87** [comment]
> Yeah, I did the (setq 'mail-user-agent 'mu4e-user-agent) ages ago. :) Don't worry, it seems to work fine. I just needed the hook. It works wonderfully, in fact. I tested it out with a nice Header/subheader thing, a nice table, bolded text etc.... it looked beautiful. Thank you very much. It looks absolutely professional. I'm loving it. :)

Hi,

can you share the relevant part of your .spacemacs config file?

I can't for the life of me get to work. I put org-msg in the additional-packages section, and copied the hook above in the user-config section.

When I compose to a new email, it does go into org-msg mode but I cannot send the email or preview it.

I get the error 

`Symbol's function definition is void: org-collect-keyboards`.

I recently moved to emacs and so I am not really sure how to address this.
