### ISSUE TITLE
adding courier font command

### ISSUE THREAD

**Issue by danielgoldin** [jeremy-compostella/org-msg#187]
I realize that In am supposed to use org-msg-enforce-css, but I pulled some code off another post and it didn't show up in the email I created.

```
(defconst org-msg-default-style
  (let* ((font-family '(font-family . "\"Courier\""))
	 (font-size '(font-size . "12pt"))
	 (font `(,font-family ,font-size))
	 (line-height '(line-height . "12pt"))
	 (bold '(font-weight . "bold"))
	 (theme-color "#0071c5")
	 (color `(color . ,theme-color))
	 (table `(,@font (margin-top . "0px")))))


(defcustom org-msg-enforce-css org-msg-default-style
  "Define how to handle CSS style:
- list - style definition: see `org-msg-default-style' for
  example.
- string - path to a CSS file: same as t but use this file
  definitions."
  :type '(choice (file :must-match t)
		 (list (list symbol symbol
			     (alist :value-type string)))))

```

I'm a non-programmer who use org-mode to write academic papers. I'm loving org-msg and this is the last tweak I need to make.

**Comment by danielfleischer** [comment]
Your code is wrong; you are missing the punchline in the let block:
`(let* ((bunch of definitions)) (punch line))`
You defined a bunch of variables and then you return nothing. 

Go back to the variable definition and copy everything and **then** put your own modifications.

**Comment by danielgoldin** [comment]
Worked like a charm. Thank you so much for your help and for creating org-msg.

**Comment by jeremy-compostella** [comment]
Great ! ☺️
