### ISSUE TITLE
Incompatible with BBDB

### ISSUE THREAD

**Issue by ericsfraga** [jeremy-compostella/org-msg#2]
Like you, I would rather avoid HTML emails but I do have to use them sometimes and this package looks quite nice. However, it doesn't work with bbdb, or more properly, bbdb doesn't know about org-msg. I get the following error:

`Debugger entered--Lisp error: (error "BBDB: MUA ‘org-msg-edit-mode’ not supported")`
`  signal(error ("BBDB: MUA ‘org-msg-edit-mode’ not supported"))`
`  error("BBDB: MUA '%s' not supported" org-msg-edit-mode)`
`  bbdb-mua()`
`  bbdb-mua-update-records(nil bbdb-select-message)`
`  bbdb-mua-auto-update()`
`  run-hooks(message-send-hook)`
`  message-send(nil)`
`  message-send-and-exit()`
`  org-msg-ctrl-c-ctrl-c()`
`  run-hook-with-args-until-success(org-msg-ctrl-c-ctrl-c)`
`  org-ctrl-c-ctrl-c(nil)`
`  funcall-interactively(org-ctrl-c-ctrl-c nil)`
`  call-interactively(org-ctrl-c-ctrl-c nil nil)`
`  command-execute(org-ctrl-c-ctrl-c)`

**Comment by jeremy-compostella** [comment]
Could you evaluate the following and tell me if it works for you ?

(add-to-list 'bbdb-mua-mode-alist  '(message org-msg-edit-mode))

**Comment by jeremy-compostella** [comment]
I have pushed a change which should take care of this issue.  Could you please verify that it works for you?

**Comment by jeremy-compostella** [comment]
I consider the issue closed.  Thanks for the report.
