### ISSUE TITLE
org-msg mu4e reply to msg problem

### ISSUE THREAD

**Issue by ronscho** [jeremy-compostella/org-msg#20]
emacs 26.3
OSX 10.15.1

I can compose E-Mails with org-msg without any problems. But when I replay to a message from my inbox pressing 'R', the default mu4e compose mode will open and send an text-only message not an html message.

Is there some option I forget to include in my configuration?

Best regards
Ronny

**Comment by ronscho** [comment]
After testing org-msg on my working machine, I get the following Error

"error in process filter: No buffer named *Article*

Is it possible there is some sort of problem with a temporary buffer for repling with mu4e?

**Comment by jeremy-compostella** [comment]
Hi **Ronny**,

Do you have the Mail User Agent variable properly set ? (see [README](https://github.com/jeremy-compostella/org-msg) **Configuration** section).

Regards,
**Jeremy**

**Comment by ronscho** [comment]
Hi Jeremy,

Yes, I think the Mail User Agent is properly set. 
```
(require 'org-msg)
(setq mail-user-agent 'mu4e-user-agent)
```
Composing E-Mail with org-msg is no problem, but responding does not work quite yet ;).

But this piece of software is awesome, thank you so much for your efforts.

Regards,
Ronny

**Comment by ronscho** [comment]
Ok, 
I started emacs with `--debug-init` and if I'm in mu4e header-view and reply to the current message, I get the following error.

```
(error "No buffer named *mu4e-view*")
 org-msg-article-htmlp-mu4e()
  apply(org-msg-article-htmlp-mu4e nil)
  org-msg-mua-call(article-htmlp)
  org-msg-post-setup()
  run-hooks(change-major-mode-after-body-hook text-mode-hook message-mode-hook mu4e-compose-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook message-mode-hook mu4e-compose-mode-hook))
  run-mode-hooks(mu4e-compose-mode-hook)
  mu4e-compose-mode()
```

If I'm in the buffer mu4e-view, after opening the current message from header-view, I get the following error.

```
 (error "No buffer named *Article*")
  org-msg-article-htmlp-mu4e()
  apply(org-msg-article-htmlp-mu4e nil)
  org-msg-mua-call(article-htmlp)
  org-msg-post-setup()
  run-hooks(change-major-mode-after-body-hook text-mode-hook message-mode-hook mu4e-compose-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook message-mode-hook mu4e-compose-mode-hook))
  run-mode-hooks(mu4e-compose-mode-hook)
  mu4e-compose-mode()
```

**Comment by jeremy-compostella** [comment]
I don't know how to help further.  Could you try to debug more on your side.  Try to identify why the buffer cannot be accessed for instance.  I don't use mu4e (I uses gnus) so I can't experiment but many people are using OrgMsg with mu4e.

**Comment by ronscho** [comment]
I guess we can close this issue for now. I solved the problem by removing Emacs and installing emacs-plus via homebrew.

So far I have no problems with replying to messages.

**Comment by jeremy-compostella** [comment]
OK
