### ISSUE TITLE
Message content disappears in replies 

### ISSUE THREAD

**Issue by EinarElen** [jeremy-compostella/org-msg#21]
When sending replies, the actual content of the reply (everything between the two separators) disappears. 

As far as I can see it is not connected to mu4e in particular. mail-user-agent is set. Configuration same as the default one. 

Example:
```
From: Einar Elén <einar.elen@gmail.com>
To: einar.elen@gmail.com
Subject: Re: 
Date: Wed, 27 Nov 2019 16:38:32 +0100
In-reply-to: <87lfs1s6wr.fsf@gmail.com>
Fcc: /home/einarelen/.Maildir/gmail/[Gmail]/Sent Mail/cur/1574869112.10c3f1c2a33b0667.elfriede:2,S
--text follows this line--
#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: ("/tmp/87lfs1s6wr.fsf@gmail.com")
:attachment: nil
:END:
t
--citation follows this line (read-only)--
Einar Elén writes:

f 

```

produces
`<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="generator" content="Org mode"/><meta name="author" content="Einar Elén"/></head><body><nil/><div align="left"><b>
From</b>: &quot;Einar Elé<a href="mailto:n&quot; &lt;einar.elen@gmail.com&gt;">n</a><br/><b>
Subject</b>: <br/><b>
To</b>: <a href="mailto:nil &lt;einar.elen@gmail.com&gt;">nil</a><br/><b>
Cc</b>: <br/><b>
Date</b>: Wed, 27 Nov 2019 15:57:54 +0100<br/></div>
<hr/><div style="font-family:Garamond, EB Garamond, Georgia, Arial, Serif;font-size:10pt;line-height:11pt;" id="content">
<p style="text-decoration:none;margin-bottom:0px;margin-top:10px;line-height:11pt;font-size:10pt;font-family:Garamond, EB Garamond, Georgia, Arial, Serif;max-width:100ch;">
f
</p>
</div>
</body></html>
`

Using Emacs 27, mu 1.3.5, msmtp 1.8.6

**Comment by jeremy-compostella** [comment]
This is not clear to me.  Do you mean that the 't' that we should expect above the separator is missing ?

**Comment by EinarElen** [comment]
Basically, anything that should be above the separator is missing. Should've included a more demonstrative example. I found the culprit however, this occurs when org-html-html5-fancy (from ox-html) is set to t.

**Comment by jeremy-compostella** [comment]
Hi **Einar Elén**,

Thanks for pointing out the culpirit.  It seems that the issue has been introduced when Matt Price was trying to support this `org-html-html5-fancy` flag (see commit [Allow fancy html5 ARTICLE tag during exportation](https://github.com/jeremy-compostella/org-msg/commit/a9af8f7fcd8ca6fff7024cec0ccac71c22e1478e)). I have been able to reproduce the issue you reported and I made a fix, see [Fix org-html-html5-fancy management](https://github.com/jeremy-compostella/org-msg/commit/ce6e72d2bc8b95ae9e0fc76888f7c11295e6de7d).  Let me know if it fixes the issue for you.

Regards,

-**Jeremy**   
*One Emacs to rule them all*

**Comment by EinarElen** [comment]
This fixes the issue. Thanks, now I can start using org-msg full time :)
