### ISSUE TITLE
What if mail-user-agent is gnus-user-agent

### ISSUE THREAD

**Issue by dingesista** [jeremy-compostella/org-msg#22]
Hello Jérémy and others,

How difficult would it be to support mail-user-agent being gnus-user-agent, so that gcc are created? If I can help, I'd be very happy to

currently, I get:

Debugger entered--Lisp error: (error "Backend not found").

**Comment by jeremy-compostella** [comment]
Hi **Dingesista**,

> How difficult would it be to support mail-user-agent being gnus-user-agent, so that gcc are created? If I can help, I'd be very happy to

Well this should actually be really cheap as it should already be supported.  I pushed patch [gnus: restore the gnus user agent support](https://github.com/jeremy-compostella/org-msg/commit/31a93a9e239a51b43e80b76b8d7a5f5345c93fb5) on the [experimental](https://github.com/jeremy-compostella/org-msg/tree/experimental) branch.  I think that it should take care of this.

Regards,

**Jeremy**   
*One Emacs to rule them all*

**Comment by dingesista** [comment]
Thank you Jérémy!

This works for creating and sending emails (thanks!) but somehow I'm not (yet) seeing the sent messages ( Gcc ) appear. Will take a closer look

**Comment by jeremy-compostella** [comment]
Hi **Dingesista**,

If I set `mail-user-agent` to `gnus-user-agent`, I get the `Gcc:` header.  However, I notice another issue.  When  `mail-user-agent` is set to `gnus-user-agent` the `org-msg-post-setup()` is called twice and this creating some issues.  I fixed this with [gnus: fix multiple \`org-msg-post-setup' calls](https://github.com/jeremy-compostella/org-msg/commit/7c7e94e506a3b9410f9c2a0f0558c7794026e8b3).  Let me know if it works for you.

Regards,

-**Jeremy**   
*One Emacs to rule them all*

**Comment by dingesista** [comment]
Hello Jeremy,
Much appreciated! You are right the Gcc header is in the message, but it seems not to be used. I see this in the *Messages* buffer: 
Unable to open server nnimap due to: /imaps Name or service not known

I don't know (yet) if that is my set up, or org-msg, 

Re the org-msg-post-setup() being called twice. That happens, but not consistently. I will report back!

Thanks

**Comment by dingesista** [comment]
Hi Jeremy!
Using that (latest) version, everything works.: including gcc. Thanks a lot!

**Comment by jeremy-compostella** [comment]
Perfect, I have pushed the experimental branch as the new master branch.
