### ISSUE TITLE
Forwarding emails in mu4e does not include original attachments

### ISSUE THREAD

**Issue by nxtruong** [jeremy-compostella/org-msg#23]
I'm using `org-msg` with `mu4e`. When I forward an email with attachments, with `org-msg-mode` enabled, the attachments in the original email are included at the bottom of the editing buffer (in the read-only citation section) but not automatically included in the PROPERTIES drawer. When the email is sent (forwarded), the original attachments are not included in it. This behavior is unexpected because by default, the attachments in the original email should be included in and sent with the forwarded email. If `org-msg-mode` is disabled, the plain-text forwarded email in `mu4e` automatically includes and sends all the original attachments with it.

**Comment by jeremy-compostella** [comment]
I am aware of it.  Mail forwarding is a not well supported use-case.  If you are motivated to create the right advice function for mu4e in order to perform that job, I would be more than happy to review your patches.
