### ISSUE TITLE
GPG-Support missing(?)

### ISSUE THREAD

**Issue by mgrunwald** [jeremy-compostella/org-msg#26]
GPG Support is missing. At least, I didn't find a way to sign a mail. Even if I call `mml-secure-sign`, the tag `<#part sign=pgpmime> ` stays in the file/mail, but there is no signature.

Is there a way to achieve that?

(Btw: I just love org-msg mode :) )

**Comment by jeremy-compostella** [comment]
Hi,

Please have a look at #24, if as I expect this is the same request:
1. close this ticket
2. provide feedback and inputs on #24  

Regards,
Jeremy

**Comment by dakling** [comment]
Hi,

I just wanted to quickly ask what the current state of this feature is. For me, signing mails with `mml-secure-sign-pgpmime` and viewing them inside emacs works, however, the Outlook web interface doesn't display the mails properly - it just displays three attachments (signature.asc, some-file.htm, some-file.txt), without acutally displaying the message contents. Is this just a limitation of Outlook, or would you expect it show the message normally? (When composing and signing mails without `org-msg`, Outlook displays the message normally, though it shows a message that digital signature verification is not supported)

Regards,
Dario

PS: thanks for your work on this awesome package!

**Comment by jeremy-compostella** [comment]
Using `mml-secure-sign-pgpmime` works for me.  Outlook displays the message normally, though it shows a message that digital signature verification is not supported.

However, if I use the `mml-secure-sign` function, I get the same result than you:  it just displays three attachments (signature.asc, some-file.htm, some-file.txt).
