### ISSUE TITLE
Multipart alternative

### ISSUE THREAD

**Issue by mgttlinger** [jeremy-compostella/org-msg#29]
This currently sends a `multipart/related` of the HTML message plus any attachments. I would also like to send a plaintext or org encoded version of the message for MUAs that don't support HTML messages. This should be placed inside a `multipart/alternative`.

From playing around in the implementation I was able to send the plain variant but this breaks things due to the enclosing `related` environment and also attachments were missing then.

**Comment by jeremy-compostella** [comment]
Hi,

To implement this properly it requires a fix of the `mml-generate-mime` function.  I submitted a patch to the emacs-bug mailing list in January but it did not get any attention... :/  I just submitted a patch to the emacs-devel mailing list (see https://lists.gnu.org/archive/html/emacs-devel/2020-02/msg00179.html) today,

With this patch merged, I should be able to get rid of of the `org-msg-mml-into-multipart-related` advice hack that I had to put in place and it should also be very easy to implement your "text/plain" feature.

In the meantime, I have an experimental implementation which I pushed on the `experimental` branch if you want to give it a try.

Regards,
Jeremy

**Comment by mgttlinger** [comment]
Sorry for the late reply. 

I just tested it and it works great! Thank you very much for implementing this so quickly! The only complaint I have is that the ASCII export starts with the Author value in the text which I wouldn't expect in an email.

**Comment by jeremy-compostella** [comment]
The patch include a change of the `org-msg-options` customizable variable to cover this. 

I'll try to find some time to finalize this patch and include it in the master branch.

**Comment by jeremy-compostella** [comment]
Merged.
