### ISSUE TITLE
org-msg does not work well with mu4e when mu4e-view-use-gnus is set to true

### ISSUE THREAD

**Issue by guibor** [jeremy-compostella/org-msg#30]
org-msg-post-setup skips the important parts due to org-msg-mua-call returning nil when needed.

**Comment by jeremy-compostella** [comment]
You'll have to problem more details.  FYI, I use gnus not mu4e...

**Comment by mgttlinger** [comment]
I will investigate this later this week when I find time. I use mu4e with the gnus view which works fine for writing emails but when replying to emails this messes things up.

**Comment by bepolymathe** [comment]
I keep an eye on this discussion too... for same reason mu4e + gnus view
