### ISSUE TITLE
Underlined text not styled

### ISSUE THREAD

**Issue by obar** [jeremy-compostella/org-msg#31]
With `_input text_` one gets:

```
<span class="underline">input text</span>
```

But since you can expect global css to be removed in email clients, this doesn't work. A better output would be:

```
<span style="text-decoration: underline">input text</span>
```

(Or alternatively `<u>` tags)

This is using Org 9.3.4

**Comment by jeremy-compostella** [comment]
Hi,

Good catch. I almost never use underlined text and the preview in firefox looks good (it seems that firefox implements a default style for class `underline`) so I never figured out that this was not working properly.

I made a simple fix for this and pushed a patch to the experimental branch.  Could you give verify that it works for you too ?

Regards,
Jeremy

**Comment by obar** [comment]
Just tried it out in a browser-based client and in emacs with notmuch looking at the prettified html.

Underline with spans as per this patch works in the browser(!) but didn't work in emacs.

I did another test and  `<u>` tags work in both emacs and the browser, as well as nested with other tags.

Digging into it a little more, perhaps it's worthwhile locally setting `org-html-text-markup-alist` (see ox-html.el) for the export? That way org-msg is immune to unrelated user customizations of that list, and you can emit `<u>` tags. By default it has `(underline . "<span class=\"underline\">%s</span>")` (in a list with a few other tag types), if it was `(underline . "<u>%s</u>")` that would do the trick.

**Comment by jeremy-compostella** [comment]
Now this is not an `org-msg` bug, this is a limitation of mail reader.  Truly HTML Mail reader are capable of reading it (I verified). 

Which mean that at this point, if you want to be able to see in your emacs notmuch reader, you'll have to improve notmuch rendered or to change your configuration as follow to send email with the `<u>` tag as you suggested.  My point is `org-msg` is not the right spot to fix that second issue,

```
(eval-after-load 'ox-html
  (setf (alist-get 'underline org-html-text-markup-alist) "<u>%s</u>"))
```  


Regards,
Jeremy

**Comment by obar** [comment]
Very fair! My tests were very limited :) Thanks for fixing that bug
