### ISSUE TITLE
How to modify color of headings?

### ISSUE THREAD

**Issue by WhatDothLife** [jeremy-compostella/org-msg#34]
I switched to org-msg from org-mu4e-compose-mode and I'm enjoying it so far. The only thing that bothers me, is that I don't know how to change the values that determine the rendering of headings.
The mail I sent to myself looks like this.
![org-msg](https://user-images.githubusercontent.com/33008303/75626750-0c844700-5bc2-11ea-8a90-33fb0680536a.png)

I want first and second level headings to be colored in black and remove the underlining of the second level headings. How do I do this?

**Comment by jeremy-compostella** [comment]
Hi,

I you read the documentation, you would see that you can customize the `org-msg-enforce-css` variable to change the style.  You could just create you own, copy the default and make some changes, or just make some changes to the current configuration after the `org-msg` module has been loaded from your own configuration, see below example:

```
(eval-after-load 'org-msg
  `(progn
     ;; Set headline level 1, 2 and 3 black
     (dolist (tag '(h1 h2 h3))
       (let ((cur (cdr (alist-get tag org-msg-enforce-css))))
	 (setcar cur (assq-delete-all 'color (car cur)))
	 (push (cons 'color "black") (cadr (alist-get tag org-msg-enforce-css)))))
     ;; Remove underline on headline level 3
     (let ((cur (cdr (alist-get 'h3 org-msg-enforce-css))))
       (setcar cur (assq-delete-all 'text-decoration (car cur))))))
```

Regards,
Jeremy

**Comment by jeremy-compostella** [comment]
Can I close it now ?

**Comment by WhatDothLife** [comment]
Yes, I read the documentation but found the modification of the variable to difficult to understand. I'll reopen it, if there are any more questions. Thanks.

**Comment by runekaagaard** [comment]
I've had good results for both outlook and gmail simply using no custom styles at all. I have this in my init.el:

    (setq org-msg-enforce-css "/path/to/an/empty/file.css")

**Comment by jeremy-compostella** [comment]
Good.  Note that you will likely start running into some formatting issue with such a solution when you will reply to emails making strong use of CSS.
