### ISSUE TITLE
Commenting in line

### ISSUE THREAD

**Issue by guibor** [jeremy-compostella/org-msg#36]
Hi! 

Thanks for the wonderful package, it has definitely improved my life :).

At times I need to respond to mails in-line (=CIL) - since the citation is read-only, how do you suggest going about this?

**Comment by guibor** [comment]
Does anyone have a recommendation?

Thanks!

**Comment by guibor** [comment]
Detailing my solution.

I added the following function:


`(defun add-citation ()
  (interactive)
  (save-excursion
    ;; We defined in org-msg.el:
    ;; (setq-local original (buffer-substring (org-msg-end) (point-max)))
    (insert "\n\n------\n")
    (insert "#+BEGIN_VERSE\n")
    (insert (s-join "\n   " (cdr (s-lines original))))
    (insert "\n#+END_VERSE")
    )
  )

(define-key org-msg-edit-mode-map (kbd "M-.") 'add-citation)
`

After adding a buffer local variable to the derived mode in org-msg.el

`
(define-derived-mode org-msg-edit-mode org-mode "OrgMsg"
...
(setq-local original (buffer-substring (org-msg-end) (point-max)))
...
)
`
I can then add comments in line. I still have some issues creating a different style for the comments, though.

**Comment by guibor** [comment]
Regarding  having a different style for comments,  I opened a separate  issue:
https://github.com/jeremy-compostella/org-msg/issues/38

**Comment by jeremy-compostella** [comment]
Hi,

In general there is no solution to edit the original content in org-msg.  The reason is we would need to implement some kind of HTML parser, be able to match positions, split tags to insert in between, ...

I don't understand your solution.

FYI, what I usually do is I copy the pieces I want to respond to and put them between `#+begin_quote` `#+end_quote`.  The default quoting style is indented, italic and grey background.

Regards,

Jeremy

**Comment by guibor** [comment]
Thanks!

What this solution does, is creates a variable and shortcut through which one can easily paste the citation, wrapped into the "verse" environment. "Quote" works indeed better - so this would become:

```
(defun add-citation ()
  (interactive)
  (save-excursion
    ;; We defined in org-msg.el:
    ;; (setq-local original (buffer-substring (org-msg-end) (point-max)))
    (insert "\n\n------\n")
    (insert "#+BEGIN_QUOTE\n")
    (insert (s-join "\n   " (cdr (s-lines original))))
    (insert "\n#+END_QUOTE")
    )
  )
```

I then use 
```
(add-to-list 'org-structure-template-alist '("Q" "#+END_QUOTE\n?\n#+BEGIN_QUOTE\n"))
```
to easily wrap a comment in line.

Reg. the default quoting style - where is that set and how can I customize it? Everything works fine, but the font color is changed to my default response font color (configured in the css variable in org-msg).

**Comment by jeremy-compostella** [comment]
In the default style (`org-msg-default-style` variable) look for `blockquote`.  Note that I don't choose the tag names org mode does.
