### ISSUE TITLE
Footnote

### ISSUE THREAD

**Issue by bepolymathe** [jeremy-compostella/org-msg#40]
Hi,

Thank you for this very useful tool that I recently discovered. 

I have a strange behavior with footnotes.  The content of the note appears above the number. 

![image](https://user-images.githubusercontent.com/29939805/78460141-c0478d80-76be-11ea-8023-06bc7bd73c34.png)

Do you have the same behavior?

**Comment by jeremy-compostella** [comment]
I also observe this issue with a regular org-mode buffer exported as html.

**Comment by bepolymathe** [comment]
And do you think there is a work around solution ?

**Comment by jeremy-compostella** [comment]
I don't I would suggest to hack `ox-html`.
