### ISSUE TITLE
Send inline image attachment

### ISSUE THREAD

**Issue by pawsen** [jeremy-compostella/org-msg#41]
As per [difference to org-mime](https://github.com/jeremy-compostella/org-msg/issues/1), it is possible to send images as inline.
How do I do that? I have not been able to figure it out.

Best regards,
Paw

**Comment by jeremy-compostella** [comment]
Well just put your image as in any org mode file:

``
Hi,

[[/home/user/Pictures/signing for fw.JPG]]

Regards,

#+begin_signature
-- *Jeremy* \\
/One Emacs to rule them all/
#+end_signature
``
