### ISSUE TITLE
Sending via mu4e fails

### ISSUE THREAD

**Issue by wedens** [jeremy-compostella/org-msg#43]
Whenever I compose a message using org-msg and try to send it, I get this error:
```
Debugger entered--Lisp error: (wrong-number-of-arguments #f(compiled-function (path maildir) #<bytecode 0xc17121>) 1)
  mu4e~proc-sent("/maildir/drafts/cur/1588137829.ecfa2055d18955a4.xxx:2,DS")
  #f(compiled-function () #<bytecode 0x19953f9>)()
  run-hooks(message-sent-hook)
  message-send(nil)
  message-send-and-exit()
  org-msg-ctrl-c-ctrl-c()
  run-hook-with-args-until-success(org-msg-ctrl-c-ctrl-c)
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

I believe the error occurs somewhere in this code https://github.com/jeremy-compostella/org-msg/blob/master/org-msg.el#L1096 introduced in #42

/cc @podiki 

Emacs 27
org-msg: 2.7
mu4e: 1.2.0
OS: Linux

**Comment by podiki** [comment]
I'm guessing this is because of changes in `mu4e` since 1.2.0, which is a year old now. Can you try with the latest version, or at least 1.4?

**Comment by jeremy-compostella** [comment]
I have indeed no desire to support old version of mu4e.

**Comment by podiki** [comment]
@wedens can you confirm if you upgrade mu4e to a more recent version that everything works?

Assuming that is the case, and since this change was made several mu4e versions ago, then this should be closed.

**Comment by gspe** [comment]
Hi,
for me, using last version of `mu4e` and `org-msg` , sending email is working right.
I don't have this kind of problem.

**Comment by wedens** [comment]
I'm having some issues after mu/mu4e upgrade (https://github.com/djcb/mu/issues/1667#issuecomment-623873395), so I can't say for sure. But it seems to get past this code successfully.
