### ISSUE TITLE
Sending failed with recent emacs

### ISSUE THREAD

**Issue by JulienMasson** [jeremy-compostella/org-msg#44]
Hi @jeremy-compostella,

Thanks again for all the work you have done around `org-msg` :)

I compile manually emacs and today after updating the source code I have the following error when I send an email with `org-msg` enabled:
```
Debugger entered--Lisp error: (wrong-type-argument listp part)
  mml-compute-boundary-1(part)
  mapc(mml-compute-boundary-1 (part (type . "text/html") (disposition . "inline") (tag-location . 239) (contents . "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"e...")))
  mml-compute-boundary-1((multipart (type . "mixed") part (type . "text/html") (disposition . "inline") (tag-location . 239) (contents . "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"e...")))
  mml-compute-boundary((multipart (type . "mixed") part (type . "text/html") (disposition . "inline") (tag-location . 239) (contents . "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"e...")))
  mml-generate-mime-1((multipart (type . "mixed") part (type . "text/html") (disposition . "inline") (tag-location . 239) (contents . "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"e...")))
  mml-generate-mime(nil nil)
  message-encode-message-body()
  message-send-mail(nil)
  message-send-via-mail(nil)
  message-send(nil)
  message-send-and-exit()
  org-msg-ctrl-c-ctrl-c()
  run-hook-with-args-until-success(org-msg-ctrl-c-ctrl-c)
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

Emacs version:
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.11, cairo version 1.16.0) of 2020-04-30

I've tested with only `org-msg` (no other configuration or modules loaded).

In the emacs source code my head is currently at this commit:
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3c810669f7b913f63049826a89e08c1691767506

I have investigated a little bit and it looks like it's due to this change:
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3c443e990f933409ab6ab01a5a20097ad86929fd

When I revert this commit `3c443e990f933409ab6ab01a5a20097ad86929fd`, it works fine.

For the moment I did not have time to find a "proper" solution ...

**Comment by jeremy-compostella** [comment]
Hi Julien,

Long time no talk.  I really hope you are doing well in this uncertain times.

I believe that the issue you are experiencing is similar to #39 and I would expect the same fix to resolve it.  Please update `org-msg` and make sure that you have commit `e964bee1fa14ff5e8acf69c34754f8059cc84af9`.

For your information, I fixed a limitation in Emacs (as you can see since you already found one of the two patches, the first one). Make sure you have both patches (they both change the `mml.el`). Then make sure you have an up to date `org-msg`.

Regards,
Jeremy

**Comment by JulienMasson** [comment]
> Long time no talk.  I really hope you are doing well in this uncertain times.

Yes it's been long time, I hope you are also doing well :)

Indeed my `org-msg` was outdated -_-, I'm still using my fork of `org-msg` for no reason ...
I have updated and now it works well.

sorry for the inconvenience.
