### ISSUE TITLE
In mu4e C-c C-k should call mu4e-message-kill-buffer

### ISSUE THREAD

**Issue by gspe** [jeremy-compostella/org-msg#45]
when use org-msg in mu4e the key combination C-c C-k should call mu4e-message-kill-buffer because if C-c C-k call message-kill-buffer the mu4e window layout will also killed.

```
mu4e-message-kill-buffer is an interactive and compiled function
defined in mu4e-compose.el.

Signature
(mu4e-message-kill-buffer)

Documentation
Wrapper around message-kill-buffer.

It restores mu4e window layout after killing the compose-buffer.

Key Bindings
mu4e-compose-mode-map C-c C-k

References
mu4e-message-kill-buffer is unused in mu4e-compose.el.
```

**Comment by jeremy-compostella** [comment]
Could you verify that https://github.com/jeremy-compostella/org-msg/commit/b117b9653cfcaef5d746146789d6039cc19ef0d5 work for you ?

**Comment by gspe** [comment]
Hi,
I've tried and work great!
Thanks again

**Comment by jeremy-compostella** [comment]
I pushed the patch to the `master` branch.
