### ISSUE TITLE
org-msg prevents mu4e~compose-mail from working as intended

### ISSUE THREAD

**Issue by tecosaur** [jeremy-compostella/org-msg#52]
Hello,

I've just started using this package, but it seems great :smiley:. One tiny hiccup though, I've found that if I call
```elisp
(mu4e~compose-mail to subject headers)
```
while `org-msg-mode` is active, none of the specified details (`to`, `subject`, `headers`) get filled in!

If it would be possible to fix this behaviour that would be marvelous :)

**Comment by obar** [comment]
I don't use mu4e but presumably you've called `(org-msg-mode)` at some point before? The relevant setup in org-msg happens when that is called:

```
(defun org-msg-mode-mu4e ()
  "Setup the hook for mu4e mail user agent."
  (if org-msg-mode
      (add-hook 'mu4e-compose-mode-hook 'org-msg-post-setup)
    (remove-hook 'mu4e-compose-mode-hook 'org-msg-post-setup)))
```

And I would guess that `mu4e-compose-mode` is used when you enter mu4e in that way.

**Comment by jeremy-compostella** [comment]
I use the venerable `gnus` so I can't really test and I would suggest that you investigate further.
FYI when I use `(compose-mail "myself" "mysubject")` it works.
