### ISSUE TITLE
message content not parsed

### ISSUE THREAD

**Issue by titaniumbones** [jeremy-compostella/org-msg#6]
Hi,

I'm using mu4 but from what I can tell this error occurs prior to any mu4e-specific code.  I tried this in a normal org-buffer:

```org-mode
* testing

- hi
#+begin_src emacs-lisp :results code
(org-msg-build)
#+end_src

#+RESULTS:
#+begin_src emacs-lisp
(html nil
      (body nil
            (p
             ((style . "text-decoration:none;margin-bottom:0px;margin-top:10px;line-height:11pt;font-size:10pt;font-family:\"Arial\";max-width:100ch;"))
             "* testing\n\n- hi\n#+begin_src emacs-lisp :results code\n(org-msg-build)\n#+end_src\n\n")))
#+end_src
```

As you can see, the buffer isn't actually being parsed, and hte raw text is just wrapped in a `p` tag.  

M-x emacs-version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10, cairo version 1.17.3) of 2019-08-30

M-x org-version: Org mode version 9.2.5 (release_9.2.5-504-g3c24be @ /home/matt/src/org-mode/emacs/site-lisp/org/)

MELPA version of org-msg  

Happy to help with debugging, but not sure where to do it.  I did try running 

```emacs-lisp
(libxml-parse-html-region (point-min) (point-max) )
```
on the HTML temp buffer, and i nthat case the fully parsed tree was returned.

**Comment by titaniumbones** [comment]
(I think I may have found the issue, see #7)

**Comment by jeremy-compostella** [comment]
I don't reproduce the issue but I am running a Emacs version 25.1.1 with org mode 9.1.1.

I don't see how I can help you further.  It seems like you are already making progress.  Keep me posted.

**Comment by jeremy-compostella** [comment]
Do you still see this issue with latest ?

**Comment by titaniumbones** [comment]
No seems to be fixed, thanks!
