### ISSUE TITLE
mu4e-compose-new cites custom mu4e signature

### ISSUE THREAD

**Issue by schoettl** [jeremy-compostella/org-msg#60]
Cool package! I'm using it with mu4e.

When I have `org-msg-mode` enabled and compose a *new* mail with mu4e, `org-msg` automatically cites my `mu4e-compose-signature`. It looks like this:

```
From: ...
...
--text follows this line--
...
--citation follows this line (read-only)--
-- 
Jakob
Phone: ...
```

Is it possible to clear the buffer for new mails or never cite anything for new mails?

I think it's reasonable to *not* use the normal MUA signature when `org-msg-mode` is enabled since in that case, often a different HTML signature is wanted.

**Comment by jeremy-compostella** [comment]
Hi,

I pushed change c4f0ef52709db1ad2550c3c6ca42e4df69a713eb on the experimental branch. I believe this should take care of this.
However, I don't know if this is going to have any adverse effect as last time I touch this algorithm was almost two years ago.  I am going to run with this change for a while.  If it works I'll merge it to the `master` branch.

In the meantime, let me know if it works for you.

Regards,
Jeremy
