### ISSUE TITLE
Send as plain text command?

### ISSUE THREAD

**Issue by cantao** [jeremy-compostella/org-msg#61]
Hi Mr. Compostella,

Thanks for the excelent work!

The behavior of org-msg, as I understood it, is to reply as plain text or html according to the message being replied to. Is there any way to, when composing a new message, intruct org-msg to send it in plain text? It's a kind of "oops, forgot to disable org-msg and don't want to copy, disable org-msg, new message, paste, send, enable it gain" thing.

Thanks a lot for your time.

**Comment by jeremy-compostella** [comment]
Hi Renato,

There is not solution designed in org-msg to create a new message as plain text.

Since the implementation relies on hook I think it would require to set a variable before you call `compose-mail`.  This is not going to be very user friendly.

Regards,
Jeremy

**Comment by cantao** [comment]
Hi!

I'm so used to org-msg by now that I have forgotten this issue!

Thank you very much for your answer, closing it right now.
