### ISSUE TITLE
Cannot send org-babel plot with org-msg (wrong file directory)

### ISSUE THREAD

**Issue by averter** [jeremy-compostella/org-msg#63]
I am trying to send an email with the org-msg+mu4e combo which contains some source code and a plot figure. The MWE below returns the correct file path for an output file when run in an org-mode file
```python
#+begin_src python :results file :exports none
  import matplotlib, numpy
  matplotlib.use('Agg')
  import matplotlib.pyplot as plt
  fig=plt.figure(figsize=(4,2))
  x=numpy.linspace(-15,15)
  plt.plot(numpy.sin(x)/x)
  fig.tight_layout()
  plt.savefig('/home/username/python-matplot-fig.png')
  return '/home/username/python-matplot-fig.png' # return filename to org-mode
#+end_src
```
However, when I run it on org-msg the resulting file does not exist and the directory is incorrect, like so
```org
#+RESULTS:
[[file:../../../python-matplot-fig.png]]
```
I would expect for the file path to be my home directory, as shown in this [video by Mike Zamansky](https://youtu.be/cPZe0AGOUJU?t=324). My configuration of org-msg is the default one, as suggested in the main webpage.

**Other info**
- I am using org 9.3.7;
- I've also asked this question on [SO](https://emacs.stackexchange.com/questions/59822/cannot-send-org-babel-plot-with-org-msg-wrong-file-directory)
- I've tested the above with Matlab or the exact dot code from Mike Z. and the same issue happens.
Finally, this is my org-babel configuration

```elisp
(setq org-export-use-babel t
      org-export-with-toc nil)
(org-babel-do-load-languages
 'org-babel-load-languages
 '((shell . t)
   (ruby . t)
   (awk . t)
   (matlab .t)
   (org . t)
   (python . t)
   (latex . t)
   (ditaa . t)
   (C . t)))

(org-link-set-parameters
 "run"
 :follow #'org-babel-ref-resolve)
(setq org-confirm-babel-evaluate (defun my-org-confirm-babel-evaluate (lang body)
                   (not (string= lang "matlab"))))  ; don't ask for matlab

(setq org-export-with-broken-links t)   ; otherwise html wont export

(require 'org-tempo)            ; sometimes org-babel breaks and this solution helps 
```

**Comment by jeremy-compostella** [comment]
Hi @averter,

I tried to reproduce your issue but I could not.

If I copy-paste your python babel block I and then I hit `C-c C-c` from inside it does create the image with the appropriate path and the following gets added to the org msg buffer (I change the path to `/tmp` but it should not make any difference).

```
#+RESULTS:
[[file:/tmp/python-matplot-fig.png]]
```

Note that if you want the image to be included in the email you have to change the `:exports none` to `:exports results`.

Regards,
Jeremy

**Comment by averter** [comment]
Thanks @jeremy-compostella, 
I've tried to comment all of my org-mode configuration except org-babel and test this again, but I get the same result. I've also changed the directory to `/tmp` and set `:exports results` as you suggested. I'm running out of ideas/tests to run.

**Comment by averter** [comment]
Finally found what the problem was. This is at the very top of my .emacs file
````elisp
;; MELPA controls
(when (>= emacs-major-version 24)  
  (require 'package)
  (setq package-archives
	'(("melpa" . "https://melpa.org/packages/")
	  ("gnu" . "https://elpa.gnu.org/packages/")
	  ;; ("org" . "http://orgmode.org/elpa/")
	  ))
  (package-initialize))
````
(note the commented line of org-mode from elpa). So I believe that I was experiencing conflicts between the org-mode version from git and the pre-packaged org-mode version that comes with emacs by default. Now everything works as expected. Thanks for your help.
