### ISSUE TITLE
Change the directory where sent messages are saved

### ISSUE THREAD

**Issue by domingoUnican** [jeremy-compostella/org-msg#65]
Dear users,

I am a newbie starting to use this nice software project.
My only complain is that, after installing org-msg, the messages that I send are saved in a different folder than before. Is there anyway to configure it? I am using  notmuch with it.

**Comment by jeremy-compostella** [comment]
That's interesting. According to #58 with notmuch sent messages are not even saved into a saved folder.  This issue is currently work in progress.

**Comment by domingoUnican** [comment]
Thanks!
