### ISSUE TITLE
Show attachments while composing like Gnus does?

### ISSUE THREAD

**Issue by happymcplaksin** [jeremy-compostella/org-msg#66]
Thanks again for this great mode!

Attaching files works fine but there is no indication that files have been attached when composing the message. Maybe you could make it look like [it does in Gnus](https://www.gnu.org/software/emacs/manual/html_node/emacs/Mail-Misc.html)?

The attachment indicators Gnus provides are comforting as in "Yes, I did remember to attach that file," plus  sometimes I attach multiple files and rely on the display to remind me which files I have already attached.

**Comment by jeremy-compostella** [comment]
What about the `:attachment:` in the `:PROPERTIES:` ?

**Comment by happymcplaksin** [comment]
Oh! I completely missed the fact that that I could expand `:PROPERTIES:`! Thank you.

**Comment by emacsomancer** [comment]
I came to ask something similar - and also hadn't thought to look in `:PROPERTIES:`. Thanks!
