### ISSUE TITLE
Including headline structures in emails and then exiting back out to "Level-0" paragraph mode

### ISSUE THREAD

**Issue by androclus** [jeremy-compostella/org-msg#67]
Hi, Jérémy --

I've always wanted to "back out" of an outline structure in org-mode, and never known how to do it.

It seems that once a structure is started, the rest of the file MUST be considered as part of that outline structure. There is no way to "break out" of the structure and go back to "Level-0" text.

(I could be wrong about this, but I have looked all over the place in the Org-Mode Manual, and have never seen anything. I've also asked on IRC to no avail.)

Now, for org-msg:

This deficiency becomes especially problematic now when using org-msg to auto-generate HTML messages.

See my pastebin, [org-mode exiting out of an outline](https://pastebin.com/T1CwkBEx).

You can see that the texts beginning with "Hello, folks!" and "Let me know" are both at what could be considered, "Level-0".

At least, I _want_ them to be.

Unfortunately, however, the way Org-mode will always treat the line beginning with "Let me know" is that it will always consider that line to be under the "Treasurer's Report" Level-2 heading. It does _not_ want to consider "Let me know" to be back at Level-0 with "Hello, folks!"

I have never been able to figure out how to get org-mode to stop doing that.

But I have settled on just dealing with it.

But now, in org-msg, I really _do_ want to put in a structure in an email, and then go back to "Level-0" and comment about that structure _from outside the structure_, just as the "Let me know" text is doing, but I cannot. (OR at least I don't know how to.)

Is there any way around this, with org-msg, so that I could use outlines in emails, but not have to make the entire rest of the email be part of that outline?  Or is there something obvious I'm just missing here?

Thank you.

**Comment by jeremy-compostella** [comment]
Unfortunately I am not aware of any solution for this as this is an org-mode limitation
