### ISSUE TITLE
Switching between text/html email

### ISSUE THREAD

**Issue by TimQuelch** [jeremy-compostella/org-msg#70]
I often want to switch between whether I send plain text email or text+html depending on who I am sending email to. Right now I manually switch between `org-msg` and `notmuch-message` modes depending which I want to send, but this is becoming unwieldy.

I'm thinking of submitting a PR which will easily allow switching between text modes. The way I was thinking was by adding more properties which control what is sent:

``` org
:PROPERTIES:
:reply-to: nil
:attachment: nil
:html: t
:text: t
:END:
```

The default values when creating a new email would be determined by a customise option.

I've had a look at the existing code in `org-msg-prepare-to-send`and I have a few questions:
- What is the deal with `org-msg-mml-recursive-support`? This evaluates to false on my computer, Which means a lot of the mime handling is done by `org-msg-mml-into-multipart-related` (as far as I can tell). `org-msg-mml-recursive-support` evaluates to true if the function `mml-expand-all-html-into-multipart-related` is defined. In what cases is this function defined?
- Are attachments handled any differently in plaintext mime vs html mime?
- I have already submitted a PR to allow customising the text export backend to give the user more control about how plain-text email looks

**Comment by TimQuelch** [comment]
I've opened a PR #71 

As far as I could tell `mml-expand-all-html-into-multipart-related` is relatively new and will recursively process all `text/html` blocks, whereas the old behabiour would not trigger recursively. This means we are required to modify the mml structure directly after parsing.

**Comment by jeremy-compostella** [comment]
We can close this issue right ?
