### ISSUE TITLE
Support drag-n-drop attachments

### ISSUE THREAD

**Issue by A6GibKm** [jeremy-compostella/org-msg#72]
mu4e supports adding attachments using drag and drop. 

When using this feature in a org-msg compose buffer, instead of adding the file to the `:attachment:` org property, or its less desirable option of adding a 
```html
<#part filename=FILEPATH disposition=attachment><#/part>
```
html tag, which is the default mu4e behaviour; it opens a buffer with the file which was dragged.

**Comment by jeremy-compostella** [comment]
Could you give a try to the patch I have pushed on the `experimental` branch ?

**Comment by A6GibKm** [comment]
I was not able to make it work, but I am also not sure if I was able to load it correctly.

**Comment by A6GibKm** [comment]
Can confirm that it is working. Thanks!
