### ISSUE TITLE
Unable to send messages on a fresh install

### ISSUE THREAD

**Issue by natecox** [jeremy-compostella/org-msg#74]
I'm just getting started with using email from emacs, and have run into a snag with org-msg I can't seem to resolve. I'm using mu4e, which seems to work fine in general (I can send and receive emails without org-msg installed).

For reference, here's the relevant config:
```emacs-lisp
(use-package mu4e
  :bind (("C-c e" . mu4e))
  :config
  (setq mail-user-agent 'mu4e-user-agent)
  (setq mu4e-maildir "~/.mail")
  (setq mu4e-get-mail-command t)
  (setq mu4e-change-filenames-when-moving t)
  (setq mu4e-sent-messages-behavior 'sent)

  ;; Set the SMTP server to office 365's defaults
  (setq message-send-mail-function 'smtpmail-send-it)
  (setq smtpmail-smtp-server "smtp.office365.com")
  (setq smtpmail-smtp-service 587))

(use-package org-msg
  :ensure t
  :after mu4e
  :init (org-msg-mode))
```

I'm able to create a new email from mu4e and I can see that the org preamble has been added without a problem. However, when I `C-c C-c` to send the message I get the following every time:
```
Debugger entered--Lisp error: (wrong-type-argument stringp html)
  file-exists-p(html)
  org-msg-prepare-to-send()
  run-hooks(message-send-hook)
  message-send(nil)
  message-send-and-exit()
  apply(message-send-and-exit nil)
  org-msg-mua-call(send-and-exit message-send-and-exit)
  org-msg-ctrl-c-ctrl-c()
  run-hook-with-args-until-success(org-msg-ctrl-c-ctrl-c)
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

Here's my emacs version:
```
GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, Carbon Version 162 AppKit 1894.6) of 2020-09-21
```

I would really appreciate any help with this!

**Comment by jeremy-compostella** [comment]
A major change has been introduced this week. I was too busy at work to
test it I only reviewed the code. Looking at the code and at your stack I
am under the impression that at line 762 and 763 there is an obvious
mistake where the alternatives and attachment variable are being
initialized. The property strings are mixed up. Try to swap the property
names and let me know if it fixes the issue. If it doesn't I suggest that
you locally revert Tim's patch and tell us if it resolves the issue.

**Comment by natecox** [comment]
PR linked above gives me a working install, thanks for pointing me in the right direction.
