### ISSUE TITLE
wrong-number-of-arguments in message-sent--hook

### ISSUE THREAD

**Issue by cnoceda** [jeremy-compostella/org-msg#78]
Hi, 
I'm getting an error when I send a mail an the debugger said is in this hook:

`  (add-hook 'message-sent-hook
            (lambda () ;;  mu4e~compose-mark-after-sending
              (setq mu4e-sent-func 'mu4e-sent-handler)
              (mu4e~proc-sent (buffer-file-name))) nil t))`

`mu4e~proc-sent` needs 2 parameters: path and maildir. Here there is just one.

Probably there is that info in the module, but I'm not a programmer :-S

Any idea to fix it.

By the way, the message is sent, but the buffer doesn't close and dont return to mu4e main window.

Thanks in advance and regards

**Update versions**
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.13) of 2019-12-24
Doom v2.0.9 (HEAD -> develop 1fba2ea30 2020-12-11 17:39:50 -0500)
mu4e - mu for emacs version 1.2.0 C

**Comment by jeremy-compostella** [comment]
I don't use the mu4e backend thus I cannot test this use-case.
I pushed a patch on the experimental branch could you give it a try?

**Comment by cnoceda** [comment]
Hi Jeremy, 
I was trying last night and I notice that in the last version of mu4e the function takes only 1 parameter, so I'm sorry for the confusion but it works well with only 1 parameter in mu4e version 1.5.7

It takes 2 parameters in mu4e version 1.2.0 

Sorry again and thank you for all.
