### ISSUE TITLE
don't hardocde 'div when parsing html

### ISSUE THREAD

**Issue by titaniumbones** [jeremy-compostella/org-msg#8]
if `org-html-html5-fancy` is non-nil, there will be no `div` elements in an exported html buffer. 

Probably simple to just let-bind a variable in org-msg-build depending on the value:

**Comment by titaniumbones** [comment]
replying to https://github.com/jeremy-compostella/org-msg/pull/7#issuecomment-527639703  : 

with a message buffer like this:

```
From: Matt Price <matt.price@utoronto.ca>
To: Matthew Price <matt.price@utoronto.ca>
Subject: Re: test
In-reply-to: <87pnkh57ga.fsf@utoronto.ca>
--text follows this line--
#+OPTIONS: html-postamble:nil H:5 num:nil ^:{} toc:nil d:nil
#+STARTUP: hidestars indent inlineimages
:PROPERTIES:
:reply-to: ("/tmp/87pnkh57ga.fsf@utoronto.ca")
:attachment: nil
:END:

Hi [[mailto:matt.price@utoronto.ca][Matthew]],

testreply

--citation follows this line (read-only)--
Matthew Price <matt.price@utoronto.ca> writes:

Test only. 


-- 
```

and `org-html-html5-fancy` set to `t`, `org-msg-build` will parse both the original and the reply, but will **fail to insert the original at the bottom of hte reply**. That's because, when it searches the paarsed tree for a `div` element, it find ony `article`. The output will look like this:

```html
<html lang="en"><head><!-- 2019-09-03 Tue 18:41 --><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="generator" content="Org mode"/><meta name="author" content="Matt Price"/></head><body><nil/>
<article id="content"><p style="text-decoration:none;margin-bottom:0px;margin-top:10px;line-height:11pt;font-size:10pt;font-family:&quot;Arial&quot;;max-width:100ch;">
Test only. </p>
</article>/body></html>
```
 
I think that #10 fixes the issue.

**Comment by jeremy-compostella** [comment]
Yeah #10  should fix this issue.  I have merge this patch that I had to fix though.

**Comment by jeremy-compostella** [comment]
Hi **Matt**,

Could you give a try to the [experimental](https://github.com/jeremy-compostella/org-msg/tree/experimental) branch that I just created and provide me your feedback ?

**Jeremy**
*One Emacs to rule them all*
