### ISSUE TITLE
result files with leading `../../../`, and HTML preview with ~/ in filenames

### ISSUE THREAD

**Issue by adl** [jeremy-compostella/org-msg#83]
I'm looking forward to use org-msg to inline pictures of automata in my email.  However currently I'm encountering a strange issue:

If I enter

```
#+begin_src dot :exports results :file test.png
  digraph {
      a -> b
      b -> c
  }
#+end_src
```
and type `C-c C-c` on it, org will generate `test.png` in the current directory (which is my home), and it will then insert

```
#+RESULTS:
[[file:../../../test.png]]
```

This is a link I cannot follow (typing Enter on it yield "File not found and directory write-protected") I would have to edit the filename in order to view it inside emacs.

When I type `C-c C-e` to preview the HTML file, I cannot see the picture either.  The HTML file passed to firefox contains `<img src="~/test.png" alt="test.png">` but I don't think firefox will understand `~/`.

When I send the email both `[[file:../../../test.png]]` and `[[file:test.png]]` seem to work fine.

**Comment by adl** [comment]
Thank you for investigating.  Looking at the `org-babel-result-to-file`, it would seem one solution is simply to 
`(setq-local org-link-file-path-type 'absolute)` while setting up the composition buffer?

**Comment by jeremy-compostella** [comment]
Sorry for the delay. I have been very busy lately.  I agree that this is likely the simplest solution and I have implemented it. It seems that this issue should be resolved on the {{experiemtal}} branch. Let me know if it also work for you.

**Comment by jeremy-compostella** [comment]
Did you get a chance to test the patches ?

**Comment by adl** [comment]
I just did.  Generating inline images with org-babel now works without problem in the composition buffer, and the image are correctly inlined in the sent email.  So this issue seem solved.

However while testing it, I discovered that SVG files seem broken in the output.

To reproduce, construct an email with:
```
#+begin_src dot :exports results :file test.png
  digraph {
      a -> b
      b -> c
  }
#+end_src

#+begin_src dot :exports results :file test.svg
  digraph {
      a -> b
      b -> c
  }
#+end_src
```

Type `C-c C-c` on both blocks before sending the email.  In the resulting email, the `test.png` is attached, while the `test.svg` is inlined.  I was unable to view the inlined SVG in either gmail or gnus (but displaying the HTML part externally with `gnus-article-browse-html-article` worked).  

I wonder if there is a way to disable inlining of SVG images and simply attach them like other images?  This would also makes more sense for the text/plain part, which contains:
```
<file:test.png>

<file:test.svg>
```

**Comment by jeremy-compostella** [comment]
The experimental branch should take care of this last issue. Could you test it ?
