### ISSUE TITLE
Org-msg not activated for mu4e-compose-reply

### ISSUE THREAD

**Issue by tiborschneider** [jeremy-compostella/org-msg#87]
Hi,
I am using org-mode with mu4e. Composing new email works as expected. But when replying to an email (with `mu4e-compose-reply`), org-msg is not activated, but mu4e-compose-mode is. 

I have ensured that the following is set (right before replying to an email):
```emacs-lisp
(setq mail-user-agent 'mu4e-user-agent)
(org-msg-mode) ; is set to 1 
```

When composing a new email (which works as expected), `(mu4e-compose 'new)` is called, and when replying to an email, `(mu4e-compose 'reply)` is executed. I use Emacs 27.1 with mu4e 1.4.13 and org-msg 20210209.2056.

Do you know what I am missing here?

**Comment by Chris00** [comment]
> when replying to an email, (mu4e-compose 'reply) is executed. 

This is normal, *org-msg* is activated by in the hook `mu4e-compose-mode-hook`.  To be triggered (for now), the original message should be HTML.  Is it your case?

**Comment by baracunatana** [comment]
Hi everyone.

I have the same issue after updating my pc (it was working fine two days ago...). Composing a new email (with `mu4e-compose-new`) works as intended, but mu4e-compose-reply doesn't activate `org-msg` (however, `org-msg-mode` evaluates to t).

I have `mu4e` 1.8.1, `org-msg` 4.0 and `emacs` 29.05. I also set `mail-user-agent` to `'mu4e-user-agent` in my config file.

Any help is appreciated.

**Comment by AbeEtan** [comment]
Hello I am having the same issue. Did we find a fix for this?
