### ISSUE TITLE
Does not handle “forward”

### ISSUE THREAD

**Issue by Chris00** [jeremy-compostella/org-msg#92]
With mu4e, pressing <kbd>F</kbd> forwards the email (as an attachment for me as I set `(setq mu4e-compose-forward-as-attachment t)`).  Then `org-msg` comes into play and does not handle the [MML](https://www.gnu.org/software/emacs/manual/html_node/emacs-mime/MML-Definition.html) present in the buffer (hence the message is useless).

**Comment by jeremy-compostella** [comment]
I have made some changes in the experimental branch and I ported your suggestion to the new design. Let me know what you think.

**Comment by Chris00** [comment]
Thanks.  It works great.  I'd just like to mention that _forward as attachment_ (for mu4e, one needs `mu4e-compose-forward-as-attachment` set to `t`, the default _forward inline_ is treated as a `reply-to-html`) is not the only case: replying to an iCal event also generates a buffer with some MML.  (Didn't find a better name to suggest unfortunately.)

**Comment by jeremy-compostella** [comment]
Understood, I reworked the code and the commit message to reflect that better. Ideally we would need to work on an actual support of MML parts but I need to find use-cases I can work on cleanly on gnus.

**Comment by Chris00** [comment]
For Gnus, you may want to set `message-forward-as-mime' to `t'.

**Comment by Chris00** [comment]
Fixed, so closing.
