### ISSUE TITLE
Question about read-only citation

### ISSUE THREAD

**Issue by cantao** [jeremy-compostella/org-msg#99]
Hi!

Quoting the docs:

> For convenience, the original message is quoted below the --citation follows this line (read-only)-- marker. So you can easily refer to the original message. However, the entire quoted text is read-only because OrgMsg does not support modification of the original content.

The `#+OPTIONS`, `#+STARTUP` and `:PROPERTIES:` blocks are fully editable, and as far as I understand, introduced by `org-msg`. If the buffer is somehow modified by `org-msg`, why cannot the original message be editable?

Forgive me if it is a dumb question, but I find awkward to duplicate portions of the original message to quote.

Thanks a lot!

**Comment by jeremy-compostella** [comment]
Because what you see in the citation area is not the HTML editable code. It is the HTML rendered by Emacs HTML engine in text form. If you modify this text form, it won't modify the HTML code and thus not the original message.
